#!/bin/bash
    
########################################################################################
### Скрипт обеспечивает передачу информации в Openahub о состоняии гостевой ОС       ###
### и автоматическое ее отключение, по прошествии времени заданного в durationwork   ###
### Он вызывается автоматически службой libvirt.                                     ###
### Ему передаются параметры:                                                        ###
### ${1} имя гостевой ОС                                                             ###
### ${2} событие с это аиртуалькой                                                   ###
########################################################################################

    
    name="[Qemu hooks]:"
    durationwork="30 minutes"
    logger "${name} Start script ${0}"
    logger "${name} Domain - $1"
    logger "${name} Event - $2"

    if [[ $1 == "ubuntu16srv" ]]
    then
        if [[ $2 == "started" ]]
        then
           #Создадим задание для cron, которое отключит ubuntu16srv 
           d=$(date -d"+${durationwork}" "+%d-%m-%Y %H-%M")
           crondate=$(date -d"+${durationwork}" "+%M %H %d %m *")
           openhabtime=$(date -d"+${durationwork}" "+%H:%M")
           logger "${name} Add cron job for shutdown ubuntu16srv after ${durationwork} at ${d}"
           croncmd="/etc/libvirt/hooks/shutdown_guest.sh ${1}"
           cronjob="${crondate} ${croncmd}"
           logger "${name} cronjob=${cronjob}"
           ( crontab -l | grep -v -F "$croncmd" ; echo "$cronjob" ) | crontab -
           
           #Изменит в Openhab состоянние на ON для QemuState_ubuntu16srv
           curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d "ON" "http://192.168.1.3:8080/rest/items/QemuState_ubuntu16srv"
           curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d "${openhabtime}" "http://192.168.1.3:8080/rest/items/QemuOffTime_ubuntu16srv"
        fi
        if [[ $2 == "release" ]]
        then
           #Изменим в Openhab состояние на OFF для QemuState_ubuntu16srv
           curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d "OFF" "http://192.168.1.3:8080/rest/items/QemuState_ubuntu16srv"
           curl -X POST --header "Content-Type: text/plain" --header "Accept: application/json" -d "--" "http://192.168.1.3:8080/rest/items/QemuOffTime_ubuntu16srv"
        fi
    fi
    exit 0